component Clock inherits Text {
	text: "00:00";

	font-family: "Montserrat";
	font-weight: 700;

	color: white;

	horizontal-alignment: center;
}

component ProgressBar inherits Rectangle {
	width: 100%;
	height: 12px;

	border-radius: 5px;
	background: black;
}

component Progress inherits ProgressBar {
	background: @linear-gradient(45deg, #33ccffee 0%, #00ff99ee 100%);
}

component Control inherits Rectangle {
	width: 100px;
	height: 30px;

	border-radius: 10px;

	background: #595959aa;

	Text {
		text: "STOP";
		font-family: "Montserrat";
		font-weight: 600;
		font-size: parent.height * 0.75;
		
		color: white;
	}

	TouchArea {
	}
}

export component MainWindow inherits Window {
	width: 300px;
	height: 175px;

	background: rgba(35, 38, 52, 0.7);	

	VerticalLayout {

		alignment: start;
		padding-left: 25px;
		padding-right: 25px;
		padding-top: 10px;

		Clock {
			font-size: (root.width)*0.25; 
		}

		ProgressBar {
			Progress { x: 0px; width: 69%; }
		}

		HorizontalLayout {
			padding-top: 15px;
			padding-bottom: 20px;

			alignment: center;
			Control { }
		}
	}
}
